const TYPE_EMOJIS = {
  'Beach': '🏖️', 'Mountain': '🏔️', 'Heritage': '🏛️', 'Adventure': '🧗',
  'Spiritual': '🛕', 'Wildlife': '🐘', 'Food': '🍜', 'Nightlife': '🌃',
  'Shopping': '🛍️', 'Nature': '🌿', 'Desert': '🏜️', 'Island': '🏝️',
  'City': '🏙️', 'Culture': '🎭', 'Romantic': '💕', 'Backpacking': '🎒'
};
const INDIA_REGIONS = ['All','North','South','East','West','Northeast','Central'];
const ASIA_REGIONS = ['All','Southeast Asia','East Asia','South Asia','Middle East','Central Asia'];

const DESTINATIONS = [
  {id:'rajasthan',name:'Rajasthan',country:'India',region:'North',capital:'Jaipur',emoji:'🏰',gradient:'linear-gradient(135deg,#e67e22,#f39c12)',bestMonths:'Oct-Mar',safetyLevel:'Safe',description:'Land of Kings – majestic forts, palaces, and golden deserts.',highlights:['Jaipur Pink City','Udaipur Lakes','Thar Desert Safari','Jaisalmer Fort'],keyPlaces:['Jaipur','Udaipur','Jodhpur','Jaisalmer','Pushkar','Mount Abu'],types:['Heritage','Desert','Culture','Shopping']},
  {id:'goa',name:'Goa',country:'India',region:'West',capital:'Panaji',emoji:'🏖️',gradient:'linear-gradient(135deg,#00b894,#00cec9)',bestMonths:'Nov-Feb',safetyLevel:'Safe',description:'India\'s beach paradise with vibrant nightlife and Portuguese heritage.',highlights:['Baga Beach','Dudhsagar Falls','Old Goa Churches','Night Markets'],keyPlaces:['Panaji','Calangute','Anjuna','Palolem','Vasco','Mapusa'],types:['Beach','Nightlife','Food','Adventure']},
  {id:'kerala',name:'Kerala',country:'India',region:'South',capital:'Thiruvananthapuram',emoji:'🌴',gradient:'linear-gradient(135deg,#00b894,#55efc4)',bestMonths:'Sep-Mar',safetyLevel:'Safe',description:'God\'s Own Country – backwaters, tea gardens, and Ayurveda.',highlights:['Alleppey Backwaters','Munnar Tea Gardens','Kovalam Beach','Periyar Wildlife'],keyPlaces:['Kochi','Munnar','Alleppey','Thekkady','Wayanad','Kovalam'],types:['Nature','Beach','Spiritual','Wildlife']},
  {id:'himachal',name:'Himachal Pradesh',country:'India',region:'North',capital:'Shimla',emoji:'🏔️',gradient:'linear-gradient(135deg,#74b9ff,#a29bfe)',bestMonths:'Mar-Jun',safetyLevel:'Safe',description:'Snow-capped peaks, apple orchards, and hill station paradise.',highlights:['Rohtang Pass','Solang Valley','Mall Road Shimla','Dharamshala'],keyPlaces:['Shimla','Manali','Dharamshala','Kullu','Spiti','Kasol'],types:['Mountain','Adventure','Nature','Backpacking']},
  {id:'uttarakhand',name:'Uttarakhand',country:'India',region:'North',capital:'Dehradun',emoji:'⛰️',gradient:'linear-gradient(135deg,#6c5ce7,#a29bfe)',bestMonths:'Mar-Jun',safetyLevel:'Safe',description:'Dev Bhoomi – land of temples, treks, and Himalayan beauty.',highlights:['Rishikesh Rafting','Valley of Flowers','Nainital Lake','Kedarnath Temple'],keyPlaces:['Rishikesh','Haridwar','Nainital','Mussoorie','Dehradun','Kedarnath'],types:['Spiritual','Adventure','Mountain','Nature']},
  {id:'tamilnadu',name:'Tamil Nadu',country:'India',region:'South',capital:'Chennai',emoji:'🛕',gradient:'linear-gradient(135deg,#fd79a8,#e17055)',bestMonths:'Nov-Feb',safetyLevel:'Safe',description:'Ancient temples, coastal beauty, and rich Dravidian culture.',highlights:['Meenakshi Temple','Marina Beach','Ooty Hills','Mahabalipuram'],keyPlaces:['Chennai','Madurai','Ooty','Kodaikanal','Rameswaram','Pondicherry'],types:['Heritage','Spiritual','Beach','Culture']},
  {id:'karnataka',name:'Karnataka',country:'India',region:'South',capital:'Bengaluru',emoji:'🏛️',gradient:'linear-gradient(135deg,#fdcb6e,#e17055)',bestMonths:'Oct-Feb',safetyLevel:'Safe',description:'IT capital meets ancient ruins – Hampi, Coorg, and coastal gems.',highlights:['Hampi Ruins','Coorg Coffee Plantations','Jog Falls','Mysore Palace'],keyPlaces:['Bengaluru','Mysore','Hampi','Coorg','Gokarna','Chikmagalur'],types:['Heritage','Nature','City','Adventure']},
  {id:'maharashtra',name:'Maharashtra',country:'India',region:'West',capital:'Mumbai',emoji:'🏙️',gradient:'linear-gradient(135deg,#636e72,#2d3436)',bestMonths:'Oct-Mar',safetyLevel:'Safe',description:'Bollywood, forts, caves, and the bustling financial capital.',highlights:['Gateway of India','Ajanta Ellora Caves','Lonavala','Mahabaleshwar'],keyPlaces:['Mumbai','Pune','Aurangabad','Nashik','Lonavala','Kolhapur'],types:['City','Heritage','Mountain','Food']},
  {id:'wb',name:'West Bengal',country:'India',region:'East',capital:'Kolkata',emoji:'🎭',gradient:'linear-gradient(135deg,#e17055,#d63031)',bestMonths:'Oct-Mar',safetyLevel:'Safe',description:'Cultural capital – Durga Puja, Darjeeling tea, and Sundarbans.',highlights:['Victoria Memorial','Darjeeling Railway','Sundarbans','Howrah Bridge'],keyPlaces:['Kolkata','Darjeeling','Siliguri','Digha','Shantiniketan','Sundarbans'],types:['Culture','Mountain','Wildlife','Heritage']},
  {id:'meghalaya',name:'Meghalaya',country:'India',region:'Northeast',capital:'Shillong',emoji:'🌧️',gradient:'linear-gradient(135deg,#00cec9,#0984e3)',bestMonths:'Oct-May',safetyLevel:'Safe',description:'Abode of Clouds – living root bridges and crystal-clear rivers.',highlights:['Living Root Bridges','Dawki River','Cherrapunji','Shillong Peak'],keyPlaces:['Shillong','Cherrapunji','Dawki','Mawlynnong','Tura'],types:['Nature','Adventure','Backpacking','Culture']},
  {id:'punjab',name:'Punjab',country:'India',region:'North',capital:'Chandigarh',emoji:'🛕',gradient:'linear-gradient(135deg,#fdcb6e,#f39c12)',bestMonths:'Oct-Mar',safetyLevel:'Safe',description:'Golden Temple, rich cuisine, and vibrant Punjabi culture.',highlights:['Golden Temple','Wagah Border','Jallianwala Bagh','Rock Garden'],keyPlaces:['Amritsar','Chandigarh','Ludhiana','Patiala','Jalandhar'],types:['Spiritual','Food','Heritage','Culture']},
  {id:'gujarat',name:'Gujarat',country:'India',region:'West',capital:'Gandhinagar',emoji:'🦁',gradient:'linear-gradient(135deg,#e17055,#fdcb6e)',bestMonths:'Oct-Mar',safetyLevel:'Safe',description:'Gir lions, white desert of Kutch, and Dwarka temples.',highlights:['Rann of Kutch','Gir National Park','Somnath Temple','Statue of Unity'],keyPlaces:['Ahmedabad','Kutch','Gir','Dwarka','Somnath','Vadodara'],types:['Wildlife','Heritage','Desert','Spiritual']},
  {id:'japan',name:'Japan',country:'Japan',region:'East Asia',capital:'Tokyo',emoji:'🗾',gradient:'linear-gradient(135deg,#fd79a8,#e84393)',bestMonths:'Mar-May',safetyLevel:'Safe',visa:'Visa Required',description:'Cherry blossoms, ancient temples, and futuristic cities.',highlights:['Mount Fuji','Fushimi Inari','Shibuya Crossing','Kyoto Temples'],keyPlaces:['Tokyo','Kyoto','Osaka','Hiroshima','Nara','Hokkaido'],types:['Culture','City','Food','Heritage']},
  {id:'thailand',name:'Thailand',country:'Thailand',region:'Southeast Asia',capital:'Bangkok',emoji:'🏝️',gradient:'linear-gradient(135deg,#00cec9,#6c5ce7)',bestMonths:'Nov-Feb',safetyLevel:'Safe',visa:'Visa on Arrival',description:'Land of Smiles – beaches, temples, street food, and nightlife.',highlights:['Grand Palace','Phi Phi Islands','Chiang Mai Temples','Full Moon Party'],keyPlaces:['Bangkok','Phuket','Chiang Mai','Krabi','Pattaya','Koh Samui'],types:['Beach','Food','Nightlife','Culture']},
  {id:'nepal',name:'Nepal',country:'Nepal',region:'South Asia',capital:'Kathmandu',emoji:'🏔️',gradient:'linear-gradient(135deg,#0984e3,#74b9ff)',bestMonths:'Oct-Dec',safetyLevel:'Safe',visa:'Visa on Arrival',description:'Roof of the world – Everest, temples, and Himalayan adventure.',highlights:['Everest Base Camp','Pashupatinath','Pokhara Lake','Lumbini'],keyPlaces:['Kathmandu','Pokhara','Lumbini','Chitwan','Nagarkot'],types:['Mountain','Adventure','Spiritual','Nature']},
  {id:'uae',name:'UAE',country:'UAE',region:'Middle East',capital:'Abu Dhabi',emoji:'🏙️',gradient:'linear-gradient(135deg,#fdcb6e,#636e72)',bestMonths:'Nov-Mar',safetyLevel:'Safe',visa:'Visa on Arrival',description:'Futuristic skylines, luxury shopping, and desert safaris.',highlights:['Burj Khalifa','Palm Jumeirah','Sheikh Zayed Mosque','Desert Safari'],keyPlaces:['Dubai','Abu Dhabi','Sharjah','Fujairah','Ras Al Khaimah'],types:['City','Shopping','Desert','Romantic']},
  {id:'singapore',name:'Singapore',country:'Singapore',region:'Southeast Asia',capital:'Singapore',emoji:'🏙️',gradient:'linear-gradient(135deg,#00b894,#fdcb6e)',bestMonths:'Feb-Apr',safetyLevel:'Safe',visa:'Visa Required',description:'Garden city – Marina Bay, hawker food, and multicultural charm.',highlights:['Marina Bay Sands','Gardens by the Bay','Sentosa Island','Chinatown'],keyPlaces:['Marina Bay','Orchard Road','Sentosa','Little India','Clarke Quay'],types:['City','Food','Shopping','Culture']},
  {id:'srilanka',name:'Sri Lanka',country:'Sri Lanka',region:'South Asia',capital:'Colombo',emoji:'🏝️',gradient:'linear-gradient(135deg,#55efc4,#00b894)',bestMonths:'Dec-Mar',safetyLevel:'Safe',visa:'ETA Required',description:'Tropical island – ancient ruins, tea trails, and pristine beaches.',highlights:['Sigiriya Rock','Ella Train Ride','Galle Fort','Yala Safari'],keyPlaces:['Colombo','Kandy','Ella','Galle','Sigiriya','Trincomalee'],types:['Beach','Heritage','Nature','Wildlife']},
  {id:'maldives',name:'Maldives',country:'Maldives',region:'South Asia',capital:'Male',emoji:'🏝️',gradient:'linear-gradient(135deg,#0984e3,#00cec9)',bestMonths:'Nov-Apr',safetyLevel:'Safe',visa:'Visa on Arrival',description:'Overwater paradise – crystal lagoons and luxury island resorts.',highlights:['Overwater Villas','Snorkeling','Bioluminescent Beach','Male City'],keyPlaces:['Male','Maafushi','Hulhumale','Baa Atoll','Ari Atoll'],types:['Beach','Romantic','Island','Adventure']},
  {id:'vietnam',name:'Vietnam',country:'Vietnam',region:'Southeast Asia',capital:'Hanoi',emoji:'🏞️',gradient:'linear-gradient(135deg,#e17055,#fdcb6e)',bestMonths:'Feb-Apr',safetyLevel:'Safe',visa:'E-Visa',description:'Ha Long Bay, street food heaven, and war history.',highlights:['Ha Long Bay','Hoi An Old Town','Cu Chi Tunnels','Sapa Rice Terraces'],keyPlaces:['Hanoi','Ho Chi Minh','Hoi An','Da Nang','Sapa','Nha Trang'],types:['Nature','Food','Heritage','Backpacking']}
];
